############################################
# CloudTechNext Select AI Analyzer inputs
############################################

variable "tenancy_ocid" {
  description = "Tenancy OCID."
  type        = string

  validation {
    condition     = length(var.tenancy_ocid) > 0
    error_message = "tenancy_ocid cannot be empty."
  }
}

variable "compartment_ocid" {
  description = "Target compartment OCID."
  type        = string

  validation {
    condition     = length(var.compartment_ocid) > 0
    error_message = "compartment_ocid cannot be empty."
  }
}

variable "region" {
  description = "OCI region, for example us-chicago-1."
  type        = string

  validation {
    condition     = length(var.region) > 0
    error_message = "region cannot be empty."
  }
}

variable "objectstorage_namespace" {
  description = "Object Storage namespace resolved by CloudTechNext for parity with Resource Manager stack variables."
  type        = string
}

variable "deployment_suffix" {
  description = "Unique suffix generated by CloudTechNext for this deployment."
  type        = string
  default     = "local0000"

  validation {
    condition     = can(regex("^[a-z0-9]{4,16}$", var.deployment_suffix))
    error_message = "deployment_suffix must be 4 to 16 lowercase alphanumeric characters."
  }
}

variable "bucket_name" {
  description = "Optional legacy Object Storage bucket override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "adb_db_name" {
  description = "Optional legacy Autonomous Database db_name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""

  validation {
    condition     = var.adb_db_name == "" || can(regex("^[A-Za-z][A-Za-z0-9]{1,13}$", var.adb_db_name))
    error_message = "adb_db_name must start with a letter, contain only letters and numbers, and be at most 14 characters."
  }
}

variable "adb_display_name" {
  description = "Optional legacy Autonomous Database display name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "autonomous_database_mode" {
  description = "Whether Select AI Analyzer should create a new Autonomous Database or use an existing one."
  type        = string
  default     = "new"

  validation {
    condition     = contains(["new", "existing"], var.autonomous_database_mode)
    error_message = "autonomous_database_mode must be new or existing."
  }
}

variable "select_ai_grant_schemas" {
  description = "Versioned demo schemas to load and expose to Select AI for a new Autonomous Database."
  type        = string
  default     = "SH_DEMO,FLEXCUBE_DEMO"

  validation {
    condition = (
      can(regex("^(SH_DEMO|FLEXCUBE_DEMO)(,(SH_DEMO|FLEXCUBE_DEMO))*$", var.select_ai_grant_schemas)) &&
      length(toset(split(",", var.select_ai_grant_schemas))) == length(split(",", var.select_ai_grant_schemas))
    )
    error_message = "select_ai_grant_schemas must be a comma-separated selection of SH_DEMO and FLEXCUBE_DEMO without duplicates."
  }
}

variable "existing_autonomous_database_ocid" {
  description = "Existing Autonomous Database OCID when autonomous_database_mode is existing."
  type        = string
  default     = ""

  validation {
    condition     = var.existing_autonomous_database_ocid == "" || can(regex("^ocid1\\.autonomousdatabase\\.", var.existing_autonomous_database_ocid))
    error_message = "existing_autonomous_database_ocid must be empty or an Autonomous Database OCID."
  }
}

variable "autonomous_database_version" {
  description = "Autonomous AI Database version to provision for Select AI Analyzer."
  type        = string
  default     = "26ai"

  validation {
    condition     = contains(["26ai", "19c"], var.autonomous_database_version)
    error_message = "autonomous_database_version must be 26ai or 19c."
  }
}

variable "autonomous_database_workload" {
  description = "Autonomous Database workload to provision for Select AI Analyzer. Use DW for Lakehouse or OLTP for Transaction Processing."
  type        = string
  default     = "DW"

  validation {
    condition     = contains(["DW", "OLTP"], var.autonomous_database_workload)
    error_message = "autonomous_database_workload must be DW or OLTP."
  }
}

variable "vcn_display_name" {
  description = "Optional legacy VCN display name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "instance_display_name" {
  description = "Optional legacy compute display name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "source_repo_url" {
  description = "Published Select AI Analyzer Git repository."
  type        = string
  default     = "https://github.com/jgangini/select-ai-analyzer.git"
}

variable "source_ref" {
  description = "Git ref to deploy from the published repository."
  type        = string
  default     = "main"
}

variable "_oci_bucket_name" {
  description = "Object Storage bucket defaults for Select AI Analyzer."

  default = {
    access_type = "NoPublicAccess"
  }
}

variable "_oci_autonomous_database" {
  description = "Scalable Autonomous Database profile for Select AI Analyzer launchpad deployments."

  default = {
    compute_count            = 4
    data_storage_size_in_tbs = 1
    db_workload              = "OLTP"
    is_auto_scaling_enabled  = true
  }
}

variable "autonomous_database_admin_password" {
  description = "ADMIN password for Autonomous Database."
  type        = string
  sensitive   = true

  validation {
    condition = (
      length(var.autonomous_database_admin_password) >= 12 &&
      length(var.autonomous_database_admin_password) <= 30 &&
      can(regex("[A-Z]", var.autonomous_database_admin_password)) &&
      can(regex("[a-z]", var.autonomous_database_admin_password)) &&
      can(regex("[0-9]", var.autonomous_database_admin_password)) &&
      !can(regex("\"", var.autonomous_database_admin_password)) &&
      !can(regex("'", var.autonomous_database_admin_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_admin_password))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_wallet_password" {
  description = "Wallet password for Autonomous Database."
  type        = string
  sensitive   = true

  validation {
    condition = (
      length(var.autonomous_database_wallet_password) >= 12 &&
      length(var.autonomous_database_wallet_password) <= 30 &&
      can(regex("[A-Z]", var.autonomous_database_wallet_password)) &&
      can(regex("[a-z]", var.autonomous_database_wallet_password)) &&
      can(regex("[0-9]", var.autonomous_database_wallet_password)) &&
      !can(regex("\"", var.autonomous_database_wallet_password)) &&
      !can(regex("'", var.autonomous_database_wallet_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_wallet_password))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_developer_password" {
  description = "Select AI Analyzer application admin password."
  type        = string
  sensitive   = true

  validation {
    condition = (
      length(var.autonomous_database_developer_password) >= 1 &&
      length(var.autonomous_database_developer_password) <= 128 &&
      !can(regex("\"", var.autonomous_database_developer_password)) &&
      !can(regex("[\\r\\n]", var.autonomous_database_developer_password))
    )
    error_message = "Application password must be 1-128 characters and cannot contain double quotes or line breaks."
  }
}

variable "app_agent_password" {
  description = "Internal APP_AGENT database password generated by CloudTechNext."
  type        = string
  sensitive   = true

  validation {
    condition = (
      length(var.app_agent_password) >= 12 &&
      length(var.app_agent_password) <= 30 &&
      can(regex("[A-Z]", var.app_agent_password)) &&
      can(regex("[a-z]", var.app_agent_password)) &&
      can(regex("[0-9]", var.app_agent_password)) &&
      !can(regex("\"", var.app_agent_password)) &&
      !can(regex("'", var.app_agent_password)) &&
      !can(regex("(?i)admin", var.app_agent_password))
    )
    error_message = "APP_AGENT password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "application_username" {
  description = "Select AI Analyzer application login username."
  type        = string
  default     = "admin"

  validation {
    condition = (
      can(regex("^[A-Za-z0-9][A-Za-z0-9_.@-]{0,127}$", var.application_username))
    )
    error_message = "Application username must start with a letter or number and can include letters, numbers, _, ., @ or -."
  }
}

variable "_oci_vcn" {
  description = "VCN defaults for the Select AI Analyzer Docker host."

  default = {
    cidr_block        = "10.10.0.0/24"
    ingress_tcp_ports = [22, 80]
  }
}

variable "_oci_instance" {
  description = "Compute instance defaults for the CloudTechNext Select AI Analyzer profile."

  default = {
    shape = {
      name          = "VM.Standard.E5.Flex"
      ocpus         = 2
      memory_in_gbs = 16
    }
  }
}
