-- Run as an Autonomous Database administrator such as ADMIN.
-- Replace __APP_AGENT_PASSWORD__ at execution time; do not commit real passwords.

DECLARE
    l_user_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO l_user_count
      FROM ALL_USERS
     WHERE USERNAME = 'APP_AGENT';

    IF l_user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER APP_AGENT IDENTIFIED BY "__APP_AGENT_PASSWORD__" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER APP_AGENT IDENTIFIED BY "__APP_AGENT_PASSWORD__" ACCOUNT UNLOCK';
        EXECUTE IMMEDIATE 'ALTER USER APP_AGENT DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
END;
/
--
DECLARE
    l_user_count NUMBER := 0;
    l_data_password VARCHAR2(128) := 'Ag' || RAWTOHEX(SYS_GUID()) || RAWTOHEX(SYS_GUID());
BEGIN
    SELECT COUNT(*)
      INTO l_user_count
      FROM ALL_USERS
     WHERE USERNAME = 'APP_AGENT_DATA';

    IF l_user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER APP_AGENT_DATA IDENTIFIED BY "' || l_data_password || '" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER APP_AGENT_DATA DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
        EXECUTE IMMEDIATE 'ALTER USER APP_AGENT_DATA ACCOUNT UNLOCK';
    END IF;
END;
/
--
GRANT CREATE SESSION TO APP_AGENT_DATA;
--
GRANT CREATE TABLE TO APP_AGENT_DATA;
--
GRANT CREATE SESSION TO APP_AGENT;
--
GRANT CREATE TABLE TO APP_AGENT;
--
GRANT CREATE VIEW TO APP_AGENT;
--
GRANT CREATE PROCEDURE TO APP_AGENT;
--
GRANT CREATE SEQUENCE TO APP_AGENT;
--
GRANT CREATE TRIGGER TO APP_AGENT;
--
GRANT CREATE SYNONYM TO APP_AGENT;
--
GRANT CREATE DATABASE LINK TO APP_AGENT;
--
GRANT CREATE USER TO APP_AGENT;
--
GRANT DROP USER TO APP_AGENT;
--
GRANT CREATE ANY TABLE TO APP_AGENT;
--
GRANT DROP ANY TABLE TO APP_AGENT;
--
GRANT INSERT ANY TABLE TO APP_AGENT;
--
GRANT SELECT ANY TABLE TO APP_AGENT;
--
GRANT EXECUTE ON DBMS_CLOUD TO APP_AGENT;
--
GRANT EXECUTE ON DBMS_CLOUD_AI TO APP_AGENT;
--
